// User Action
export const LOGIN = 'LOGIN';
export const LOGOUT  = 'LOGOUT';

// Couses Action
export const FETCH_DATA_START = 'FETCH_DATA_START';
export const FETCH_DATA_SUCCESS = 'FETCH_DATA_SUCCESS';
export const FETCH_DATA_ID_SUCCESS = 'FETCH_DATA_ID_SUCCESS';
export const FETCH_DATA_FAILED = 'FETCH_DATA_FAILED';


// Enrollment Action 

export const FETCH_ENROLLMENT_START = 'FETCH_ENROLLMENT_START';
export const FETCH_ENROLLMENT_SUCCESS = 'FETCH_ENROLLMENT_SUCCESS';
export const FETCH_ENROLLMENT_ID_SUCCESS = 'FETCH_ENROLLMENT_ID_SUCCESS';
export const FETCH_ENROLLMENT_FAILED = 'FETCH_ENROLLMENT_FAILED';
export const FETCH_UNPAID_ENROLLMENT_SUCCESS = 'FETCH_UNPAID_ENROLLMENT_SUCCESS';
export const FETCH_PAID_ENROLLMENT_SUCCESS = 'FETCH_PAID_ENROLLMENT_SUCCESS';
export const FETCH_MYCOURSES_SUCCESS = 'FETCH_MYCOURSES_SUCCESS';



